# Joel Thomas
# Project Milestone 3

### Heart Disease Risk Prediction:

In Milestone 1 I created my idea, located data and started graphical analysis. 
In Milestone 2 I will be moving on to the data preparation process of my project. After this report, my data should be ready for the model building evaluation phase.

1.) Drop Any Features that are not useful for your model building and explain why they are not useful:

In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('heart_disease_health_indicators.csv')
df.columns

Index(['HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck', 'BMI',
       'Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

I chose to drop any values that weren't metrics that could be variable per human despite circumstance they live in. Specifically health markers such has weight, smoking habits, health habits, and blood attributes.

In [65]:
##These are the columns I wiant to keep
columns_to_keep = ['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'Sex', 'Age']

#Replace DF with the columns I care about
df = df[columns_to_keep]
df.head()

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,Sex,Age
0,1,1,1,40,1,0,0,0,0,1,0,0,9
1,0,0,0,25,1,0,0,1,0,0,0,0,7
2,1,1,1,28,0,0,0,0,1,0,0,0,9
3,1,0,1,27,0,0,0,1,1,1,0,0,11
4,1,1,1,24,0,0,0,1,1,1,0,0,11

#2.) Perform any data extraction selection steps.

I really wanted to bin our ages so I can have a more useful metric to group this data before I input it into a machine learning model. I will bin them in groups of 25 below.

In [66]:
# Define the bin edges
bin_edges = [0, 25, 50, 75, 100]  # Specify the age intervals you want

# Define the labels for the bins
bin_labels = ['0-25', '26-50', '51-75', '76-100']

# Use pd.cut() to create a new column 'Age_Group' with the specified bins and labels
df['Age_Group'] = pd.cut(df['Age'], bins=bin_edges, labels=bin_labels, right=False)

# Drop the original 'Age' column if you no longer need it
df = df.drop('Age', axis=1)
df.head()

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,Sex,Age_Group
0,1,1,1,40,1,0,0,0,0,1,0,0,0-25
1,0,0,0,25,1,0,0,1,0,0,0,0,0-25
2,1,1,1,28,0,0,0,0,1,0,0,0,0-25
3,1,0,1,27,0,0,0,1,1,1,0,0,0-25
4,1,1,1,24,0,0,0,1,1,1,0,0,0-25

#3.) Transform features if necessary.

My data is luckily all Binary excluding BMI - Which I will handle in the next section for new features.

#4 Engineer new useful features.

I wanted to turn BMI into a standardized value (instead of dealing with a continuous numerical feature like BMI)

Below I istandardized the data using StandardScalar which makes the data more relative to the entire population in the study.

In [67]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df['BMI'] = scaler.fit_transform(df['BMI'].values.reshape(-1, 1))
df.head(10)

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,Sex,Age_Group
0,1,1,1,1.757934,1,0,0,0,0,1,0,0,0-25
1,0,0,0,-0.511827,1,0,0,1,0,0,0,0,0-25
2,1,1,1,-0.057875,0,0,0,0,1,0,0,0,0-25
3,1,0,1,-0.209193,0,0,0,1,1,1,0,0,0-25
4,1,1,1,-0.663145,0,0,0,1,1,1,0,0,0-25
5,1,1,1,-0.511827,1,0,0,1,1,1,0,1,0-25
6,1,0,1,0.244760,1,0,0,0,0,0,0,0,0-25
7,1,1,1,-0.511827,1,0,0,1,0,1,0,0,0-25
8,1,1,1,0.244760,1,0,2,0,1,1,0,0,0-25
9,0,0,1,-0.663145,0,0,0,0,0,1,0,1,0-25

#

#

#

#

In [69]:
X = df.drop('Stroke', axis=1)
y = df['Stroke']
df.head()

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,Sex
0,1,1,1,1.757934,1,0,0,0,0,1,0,0
1,0,0,0,-0.511827,1,0,0,1,0,0,0,0
2,1,1,1,-0.057875,0,0,0,0,1,0,0,0
3,1,0,1,-0.209193,0,0,0,1,1,1,0,0
4,1,1,1,-0.663145,0,0,0,1,1,1,0,0

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [71]:
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
X_test.head()

ValueError: could not convert string to float: '0-25'

['0-25']
Categories (4, object): ['0-25' < '26-50' < '51-75' < '76-100']